name: Deploy to Azure

on:
  push:
    branches:
      - deploy_cloud



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        

      # - name: Run Deployment Script
      #   run: |
      #    chmod +x ./Azure_Build.sh
      #    ./Azure_Build.sh
      #   env:
      #     HF_API_KEY: ${{ secrets.HF_API_KEY }}
      - name: Create and Deploy Container App
        env:
          HF_API_KEY: ${{ secrets.HF_API_KEY }}
          OMDB: ${{ secrets.OMDB }}
        run: |
           # Build and push Docker image
           docker build -t poojary9991/cs553_casestudy4 .
           docker push poojary9991/cs553_casestudy4

           # Create the Azure Container App with environment variables
           az containerapp create \
             --name casestudy4group11 \
             --resource-group CS553_CaseStudy4_group11 \
             --environment managedEnvironment-CS553CaseStudy4-aadd \
             --image poojary9991/cs553_casestudy4:latest \
             --env-vars 'HF_API_KEY'='$HF_API_KEY' \
             --ingress external \
             --target-port 7860

           az containerapp ingress enable \
             --name casestudy4group11 \
             --resource-group CS553_CaseStudy4_group11 \
             --type external \
             --target-port 7860

           # Retrieve the container app URL
           az containerapp show \
             --name casestudy4group11 \
             --resource-group CS553_CaseStudy4_group11 \
             --query properties.configuration.ingress.fqdn \
           

