name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

  # sync-to-hub:
  #   runs-on: ubuntu-latest
  #   needs: test  # This line makes sync-to-hub dependent on the test job

  #   steps:
  #     - name: Checkout for Hugging Face push
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Add remote 
  #       env:
  #         CaseStudy1: ${{ secrets.CASESTUDY3 }}
  #       run: git remote add space https://poojary9991:$CASESTUDY3@huggingface.co/spaces/ML-OPS-Grp11/CaseStudy1

  #     - name: Push to hub
  #       env:
  #         CaseStudy1: ${{ secrets.CASESTUDY3 }}
  #       run: git push --force https://poojary9991:$CASESTUDY3@huggingface.co/spaces/ML-OPS-Grp11/CaseStudy1

  # notify:
  #   runs-on: ubuntu-latest
  #   needs: test 

  #   steps:
  #     - name: Send Discord notification
  #       env:
  #         DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
  #       run: |
  #         curl -X POST -H "Content-Type: application/json" \
  #         -d "{\"content\": \"A new commit was pushed to the main branch by $GITHUB_ACTOR. 😄 CS553_CaseStudy_Group 11 rock!\"}" \
  #         $DISCORD_WEBHOOK_URL
